[tool.black]
line-length = 79
target-version = ['py36', 'py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.eggs
  | \.mypy_cache
  | \.pytest_cache
  | docs
  | locale
  | build
  | dist
  | venv
)/
'''
